# .github\workflows\ci.yml
name: CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches:
      - '**' # реагирует на push в любую ветку

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # соответствует "engines": { "node": ">=18" }
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test (if present)
        run: npm test --if-present

      - name: Build
        run: npm run build
